RebusPro/rebuspro

src/interfaces/types.tsx, src/pages/tabs/availability.tsx, src/services/userService.tsx
Give availability tab the ability to create and event using the blue circle button
=> feat: add createEvent functionality for avialability.tsx

src/interfaces/types.tsx, src/pages/tabs/availability.tsx
show recurring event in the list view of availability
ability to delete each item in the list view.
=> Show recurring

src/pages/calendar.tsx
You can now resize and drop calendar event and it will correctly update the firestore database.
=> add resize and drop functions

src/hooks/useFetchEvents.ts, src/pages/calendar.tsx, src/pages/tabs/availability.tsx
Test
1. Create a background  from availability blue circle button
- watch it populate to the availability list with the correct time
- click on the calendar Tab 
- validate that the event populates to the Calendar UI on the right Day
2. Create Background Event from the Calendar UI 
- Check the Availability Tab List to see if it populates with the right start and end times 
3. Try to Navigate Around the application and see if the Calendar UI does not fetch the events
- If it does not fetch please see if its repeatable meaning do the same action again and see if it does not populate again
=> Event resize drop

src/pages/tabs/availability.tsx
add function to dynamically convert the UTC -UTCX difference  adding hours to the display
all timestamps are stored as UTC and display to user based on their corresponding timezone.
=> fea: dynamic timezone function

src/pages/tabs/availability.tsx
in aviailabilty give the date column the ability to sort
=> feat: date sort

src/comp/AvailabilityFormDialog.tsx, src/comp/CreateBookingsFormDialog.tsx, src/comp/EventFormModal.tsx
Fixed a bug When creating event from the Calendar there should be a radio button (choice) to create Availbility or a Booking. We should think about a "default", either in settings or just start with to Availability.
=> fix:kan-71

src/app/globals.css
Take out Yellow highlight for "today" on week view and replace it with some signifier up top on the Day similar to Google Calendar
=> fix:kan-74

src/comp/tabs/create_bookings.tsx
Editing a Booking from the List view -- just like we have now with Availabilities
to follow up this task in issue ticket KAN-89
=> fix:fixing edeting listview cells

src/app/globals.css
fixing today highlight color not showing
=> fix:fixing today indicator css style

src/comp/profileTabs/bookingsTab.tsx
Create BOOKING TYPE Page small edits on verbiage
=> fix:fix kan-99

src/comp/CreateBookingsFormDialog.tsx, src/comp/EventFormModal.tsx
=> fix:fixing title of booking select

src/comp/tabs/availability.tsx
Added duration to availability
=> added duration to availability

src/comp/AvailabilityFormDialog.tsx, src/comp/CreateBookingsFormDialog.tsx, src/comp/EventFormModal.tsx, src/components/ui/dialog.tsx
=> fix:fixing dialogs overflow issue

src/app/(dashboard)/calendar/page.tsx, src/app/globals.css
This is related to Kan-87 
- Modified the events in month view to have a "dot" that represents the the booking type, and if there is no booking type , then the dot will be black color.
- added the event start time next to the event in the month view   
- removed text overflow issue on other cells in month view.
=> fix:fixing month view layout

src/app/globals.css
- Fixing a bug where day is today on monthly view and +more popover clicked, is showing the events behind the popover
- also fixing the today indicator on monthly view
=> fix:fixing popover on todays date and today day indicator change

functions/.eslintrc.js, functions/src/callable/availability/index.ts, functions/src/callable/bookings/index.ts, src/app/(dashboard)/calendar/page.tsx, src/comp/tabs/create_bookings.tsx
Re-adding the cloud function production urls
=> fix:changing the cloud functions url

src/comp/CreateBookingsFormDialog.tsx, src/comp/tabs/create_bookings.tsx
- Solving the issue where the blue plus icon doesn't create a recurring bookings 
-  deactivating the start recure input when opening the bookings modal from the blue plus icon in bookings tab
=> fix:fixing createBookingsModal for recurring events

src/comp/AvailabilityFormDialog.tsx, src/comp/tabs/availability.tsx
Related to KAN-109
Recurring availabilities where not created correctly, when creating them from availability tab blue plus button
=> fix:fixing creating recurring availabilities from availability blue plus button

package-lock.json, package.json, src/app/dashboard/bookingtypes/_components/book-types-view.tsx, src/app/dashboard/clients/_components/clients-view.tsx, src/components/ui/phone-input.tsx
related to issue ticket kan-101 
updates :
- Adding phone and email to clients page and remove default rate
=> feat:adding phone and email to clients page and remove default rate

src/app/dashboard/clients/_components/clients-view.tsx
related to issue ticket kan-101 
updates: 
- format the phone number to local number
=> fix:fixing format of the phone

src/hooks/useFetchEvents.ts
related to issue ticket 118
updates: 
- updated the events hook to prevent blinking effect when loading events when refreshing the page
=> fix:fixing the hook preventing blinking effect when loading calendar

src/app/(dashboard)/availability/_components/availability-view.tsx, src/app/(dashboard)/bookings/_components/bookings-view.tsx, src/components/forms/availabilities-form.tsx, src/components/forms/bookings-form.tsx, src/components/modals/AvailabilityFormDialog.tsx, src/lib/validations/availabilities-form-validations.ts
a partial fix related to issue ticket 128 
updates : 
- Extracted a Availabilities form to its own component and moved the state variables inside the component .
- Removed the state variables from react , and replaces with controlled state variables by React hook form library
- Created an Availability form schema to validate inputs based on their format or existence.
- made all the form inputs optional other than date, start time, end time, start recure , end recure.
- created a form action to validate the form inputs before submitting to database to prevent application braking.
- froze the form submittal until the action is completed , then redirecting to Availabilities list view page and showing the created events.
- optimizing rendering the form by removing state variable and replacing …
=> Kan 128 redo - Availabilities 

src/app/(dashboard)/calendar/_components/full-calendar.tsx, src/components/forms/calendar-form.tsx, src/components/modals/EventFormModal.tsx, src/constants/data.ts, src/lib/helpers/calendar.tsx, src/lib/helpers/events.ts, src/lib/helpers/global.ts
related to issue ticket 130 
updates : 
1- refactored adding recurring and single event code 
2- fixed a bug were date was not changing when opening the calendar modal on a specific date then changing it
=> Kan 128 redo

src/app/(auth)/_components/signup-form.tsx, src/interfaces/signups.ts, src/lib/converters/signups.ts
linking slack with account creations
=> fix:fixing slack cloud function
